version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/deployment/dam-front-end
hooks:
  ApplicationStop:
   - location: scripts/stop_server.sh
     timeout: 3600
      
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      
